feat(categorize): categories per accept values up to 6-PD-1983
pie-framework/pie-elements pull request #1179
Opened 2022-11-22 12:54 UTC by arimieandreea

2022-11-22 12:57 UTC, arimieandreea commented
The changes from categories.jsx are done to avoid the warning regarding the unique key in items in case of adding divs

2022-11-22 14:21 UTC, PatriciaRomaniuc approved these changes

2022-11-22 14:41 UTC, andreeimiron requested changes
You need to add the new config property in the documentation

2022-11-22 14:41 UTC, andreeimiron commented on packages/categorize/configure/src/design/index.jsx
> +                          min: lowerMaximumValueCategoriesPerRow,
the name is too long for this one. I think you can rename to `minCategoriesPerChoice` if I understand correctly what it refers to

2022-11-24 14:53 UTC, PatriciaRomaniuc commented on packages/pie-models/src/pie/categorize/index.ts
> +   *  Lower maximum value for categories per row
Don't you mean minimum value? If that is what it represents

2022-12-05 09:01 UTC, andreeimiron approved these changes

2022-12-05 09:05 UTC, merged