feat(complex-rubric): add validate logic PD-3260
pie-framework/pie-elements pull request #1596
Opened 2023-12-12 14:35 UTC by arimieandreea

2023-12-12 14:37 UTC, arimieandreea commented
https://illuminate.atlassian.net/browse/PD-3260

2023-12-13 09:58 UTC, andreeapescar requested changes

2023-12-13 09:58 UTC, andreeapescar commented on packages/complex-rubric/controller/src/index.js
> +  console.log(model);
Remove log.

2023-12-13 09:58 UTC, andreeapescar commented on packages/complex-rubric/controller/src/index.js
> +// this should always be updated when validate function of multi-trait-rubric is changed (as for ebsr)
“IMPORTANT! This function is a duplicate of multi-trait-rubric/controller/validate function! If you make any changes to this function, please make sure you also update multi-trait-rubric/controller/validate function!“.


Add this comment (of course, with proper "multi-trait-rubric/controller/validate function") in rubric, multi-trait-rubric and both validation functions in complex-rubric.

2023-12-13 09:58 UTC, andreeapescar commented on packages/complex-rubric/controller/src/index.js
> +const validateSimpleRubric = (model) => {
“IMPORTANT! This function is a duplicate of rubric/controller/validate function! If you make any changes to this function, please make sure you also update rubric/controller/validate function!“.

2023-12-13 11:36 UTC, merged