NLDP item type refactoring | SC-27810
pie-framework/pie-elements pull request #1615
Opened 2023-12-19 14:49 UTC by akshayhiwale

1. Added sanity checks for newly added properties in model and configuration.
2. Added comments to function and variables wherever necessary.

2023-12-20 09:05 UTC, andreeimiron approved these changes

2024-01-04 07:56 UTC, andreeapescar commented
Please don't forget to use https://github.com/semantic-release/semantic-release format for commits.

2024-01-04 07:59 UTC, andreeapescar requested changes
Please make sure you're using proper commits, as they are used in our release process to create versions and update Changelog.

2024-01-08 13:25 UTC, andreeapescar approved these changes

2024-01-08 13:25 UTC, merged