Feat(passage): Passage authoring initial UI PD-3770
pie-framework/pie-elements pull request #1957
Opened 2024-06-17 10:15 UTC by dianagociu

https://illuminate.atlassian.net/browse/PD-3770

2024-06-19 11:42 UTC, andreeapescar requested changes

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/configure/src/design.jsx
> +    const updatedPassages = model.passages.map((passage, i) => {
I guess we don't need map, we only set at [index].
Also, sanity checks

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/configure/src/design.jsx
> +
errors || {}

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/controller/src/index.js
> +export function createDefaultModel(model = {}) {
This doesn't seem to be needed?

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/controller/src/index.js
> +export const normalize = (question) => ({
Let's make we use normalize

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/docs/pie-schema.json.md
> +# `spanishInput` (boolean)
Do we need this?

2024-06-19 11:42 UTC, andreeapescar commented on packages/passage/docs/pie-schema.json.md
> +# `specialInput` (boolean)
And this

2024-06-19 11:43 UTC, andreeapescar commented
@dianagociu can you please add:
1. screenshot/video rec with authoring
2. [optional]: screenshot with how documentation looks like

2024-06-24 09:17 UTC, dianagociu commented
1. Passage Authoring Design
<img width="1710" alt="Screenshot 2024-06-24 at 11 37 50" src="https://github.com/pie-framework/pie-elements/assets/26737238/6288b0a1-7d76-4325-b4ba-9e4284efd941">
1.1Passage Authoring Settings
<img width="860" alt="Screenshot 2024-06-24 at 11 38 02" src="https://github.com/pie-framework/pie-elements/assets/26737238/ea51247e-92a0-4832-afa4-d08c2f4ee6cf">
2.1 Model for the @pie-elements/passage
<img width="496" alt="Screenshot 2024-06-24 at 12 15 29" src="https://github.com/pie-framework/pie-elements/assets/26737238/ec5a070a-a193-41ef-8371-6fb8fec00603">
<img width="698" alt="Screenshot 2024-06-24 at 12 15 33" src="https://github.com/pie-framework/pie-elements/assets/26737238/962e5c19-8e8a-4709-86c6-9d8c4825c623">
Config Object for @pie-elements/passage-configure
<img width="475" alt="Screenshot 2024-06-24 at 12 15 39" src="https://github.com/pie-framework/pie-elements/assets/26737238/bf6ff241-9237-4482-80a5-76c42faa4cd9">

2024-06-24 09:41 UTC, merged