feat(math-inline): add allowTrailingSpaces. BREAKING CHANGE: added al…
pie-framework/pie-elements pull request #553
Opened 2021-03-24 11:40 UTC by PatriciaRomaniuc

…lowTrailingSpaces to model PD-282

2021-03-25 08:25 UTC, andreeapescar commented
Let's have a new configuration property (instead of setting it directly on the model).

configuration will have a new property **allowTrailingZeros** with: settings, label, enabled & default.

If model.allowTrailingZeros is defined, we use that value. If it is not defined, we check configuration.allowTrailingZeros.default. If defined, use that value, else, use false.

Also, the checkbox has to be above all responses, instead of being in each individual response.

2021-04-07 08:00 UTC, andreeapescar requested changes

2021-04-07 09:42 UTC, andreeapescar approved these changes
Looks good. Thank you

2021-06-25 10:04 UTC, edeustace commented
lets wait until math-validation is active to see if we still need this?

2021-06-25 10:04 UTC, closed without merging