Feat(Multiple choice/grid layout
pie-framework/pie-elements pull request #608
Opened 2021-06-21 12:07 UTC by dianagociu

o have a dropdown with 3 possibilities : vertical, grid and horizontal - with vertical default. When we select grid for the layout a new setting will show up - grid Columns - which is also a dropdown with numbers between 1 and the number of choices . The selected number will represent the number of columns that we want for the grid. Right now it's w

2021-06-21 12:10 UTC, dianagociu commented
![image](https://user-images.githubusercontent.com/26737238/122759617-d11ff700-d2a2-11eb-981f-a68032849fe7.png)

2021-06-21 12:11 UTC, dianagociu commented
Horizontal Layout: 
![image](https://user-images.githubusercontent.com/26737238/122759751-f876c400-d2a2-11eb-8816-f73ad4e6d185.png)

2021-06-21 12:12 UTC, dianagociu commented
Grid Layout with 2 columns:
![image](https://user-images.githubusercontent.com/26737238/122759802-075d7680-d2a3-11eb-8665-cf8c0f221e9e.png)

2021-06-22 08:46 UTC, alextkd commented on packages/multiple-choice/src/multiple-choice.jsx
> +    const layoutClass = this.props.choicesLayout === 'grid' ? classes.gridLayout : (this.props.choicesLayout === 'vertical'? '' : classes.horizontalLayout)
I would write this more simple and more clear using `classNames({ [classes.gridLayout]: this.props.choicesLayout === 'grid', {[classes.horizontalLayout]: this.props.choicesLayout === 'horizontal' } })`

2021-06-22 08:47 UTC, alextkd commented on packages/multiple-choice/src/multiple-choice.jsx
> +        <div className={classNames(layoutClass)} style={styles.getColumns(this.props.gridColumns)}>
then you don't need to use it here

2021-06-22 08:48 UTC, alextkd requested changes
Let's make the upper improvements

2021-06-24 15:27 UTC, edeustace commented
@andreeapescar - mind managing the merge of this - looks good to me - thanks @dianagociu and @alextkd

2021-06-25 13:47 UTC, andreeapescar commented on packages/multiple-choice/configure/src/defaults.js
> +    choicesLayout: {
Since you're removing an existing property, I think it would be better to have a breaking change.

2021-06-25 13:47 UTC, andreeapescar commented on packages/multiple-choice/configure/src/main.jsx
> +  const nrOfColumnsAvailable = Array.from({length: model.choices.length}, (_, i) => i + 1);
We should add a sanity check here.

2021-07-01 10:03 UTC, andreeapescar approved these changes

2021-07-26 10:57 UTC, merged